version: '3.8'

services:
  redis:
    image: redis:latest
    platform: linux/amd64
    command: redis-server --requirepass default
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: default
    ports:
      - '6379:6379'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    ports:
      - '5432:5432'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:5679/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: WEBJS
      WHATSAPP_HOOK_EVENTS: message
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    depends_on:
      - n8n

  n8n:
    image: n8nio/n8n:latest
    platform: linux/amd64
    environment:
      WEBHOOK_URL: http://host.docker.internal:5679
      N8N_HOST: host.docker.internal
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
      # Adicionando conexão com o banco de dados Postgres
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: default
      DB_POSTGRESDB_USER: default
      DB_POSTGRESDB_PASSWORD: default
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - '5679:5678'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    depends_on:
      - postgres

  python-app:
    build: .
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      DATABASE_URL: "postgresql://default:default@postgres:5432/default"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  pgdata:
  waha_sessions:
  waha_media:
  n8n_data:
